name: Workflow for API TESTS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: API Test
      run: mvn clean test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: allure-results
        path: allure-serve/
